@startuml
(*) ---> "登录"
--->"输入账户和密码"
if "账户或密码都不为空" then
--->[false] "警告"
---> "登录"
else
--->[true] "信息传入服务器"

if "密码正确" then
--->[true] "登录成功"
---> "将用户信息以cookie形式传回前端"
if "权限管理" then
--->"身份是员工"
--->"展示员工菜单"
if "点击菜单" then
--->"销售信息管理"
---> ["只能查看自己的"] "展示销售信息"  
--->"返回菜单"
--->"展示员工菜单"
else
--->"个人信息"
---> "展示个人信息"
else
--->"退出登录"
--->"登录"
endif
else
---> "身份是经理"
---->"展示经理菜单"
if "点击经理菜单" then
---->"销售信息管理"
---->["可以增添和查看所有的"]"展示销售信息"
---->"返回菜单"
---->"展示经理菜单"
else
---->"人事信息"
---->["可以增删改查所有的"] "展示员工信息"
---->"返回菜单"
---->"展示经理菜单"
else
---->"仓储信息"
---->["可以增删改查所有的"] "展示仓储信息"
---->"返回菜单"
---->"展示经理菜单"
else
---->"个人信息"
----> "展示个人信息"
else
---->"退出登录"
---->"登录"
endif
else
---->"身份是部门领导"
---->"展示部门领导菜单"
if "点击部门经理菜单" then
---->"销售信息管理"
---->["增添和查看自己部门的"]"展示销售信息"
---->"返回菜单"
---->"展示部门领导菜单"
else
---->"仓储信息"
---->["增删改查自己部门的"] "展示仓储信息"
---->"返回菜单"
---->"展示部门领导菜单"
else
---->"个人信息"
----> "展示个人信息"
else
---->"退出登录"
---->"登录"
endif
endif
else
--->[false] "登录失败"
---> "警告"
--->"登录"

@enduml